apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nats
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /nats
        pathType: Prefix
        backend:
          service:
            name: nats
            port: 
              number: 8222
