apiVersion: apps/v1
kind: Deployment
metadata:
  name: imicros-flow-deployment
spec:
  selector:
    matchLabels:
      app: imicros-flow
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: imicros-flow
        version: '0.1'
    spec:
      containers:
      - name: imicros-flow
        image: al66/imicros-backend:latest
        imagePullPolicy: Always
        env:
        - name: SERVICES
          value: "master, acl, activity, context, control, events, feel, instance, next, query, sequence, timer"
        # Transporter settings
        - name: TRANSPORTER_NATS
          value: "nats://nats:4222" 
        # master+keys service settings
        - name: MASTER_TOKEN
          valueFrom:
            secretKeyRef:
              name: master-token
              key: token
        - name: SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              name: service-token
              key: token
        - name: SERVICE_ID
          value: "c73d1641-e677-458c-aa6b-c5a328805352"
        - name: SERVICE_AUTH_TOKEN
          value: "5506972b7d4e9f50e269df8a5aff4bfb9ed0738e0ac79aac5fd8c06c063976c5d2ff2449bdf7e4044578310bfde59f05d0a7f0c702b3ecc4d7156c7e747c45b1"
        - name: ADMIN_GROUP_ID
          value: "096f1dff-681a-4746-b5cd-2228f69630c7"
        - name: EVENT_OWNER_ID
          value: "096f1dff-681a-4746-b5cd-2228f69630c7"
        # jwt secret -> acl
        - name: JWT_SECRET
          value: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
        - name: CASSANDRA_CONTACTPOINTS
          value: "cassandra"
        - name: CASSANDRA_DATACENTER
          value: "datacenter1"
        - name: CASSANDRA_KEYSPACE_KEYS
          value: "imicros_keys"
        - name: CASSANDRA_PORT
          value: "9042"
        - name: CASSANDRA_USER
          valueFrom:
            secretKeyRef:
              name: cassandra-root
              key: user
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cassandra-root
              key: password
        # acl,control,query services settings - db
        - name: NEO4J_URI
          value: "bolt://neo4j:7687"
        - name: NEO4J_USER
          valueFrom:
            secretKeyRef:
              name: neo4j-root
              key: user
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j-root
              key: password
          