apiVersion: apps/v1
kind: Deployment
metadata:
  name: imicros-flow-deployment
spec:
  selector:
    matchLabels:
      app: imicros-flow
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: imicros-flow
        version: '0.1'
    spec:
      containers:
      - name: imicros-flow
        image: al66/imicros-backend:latest
        imagePullPolicy: Always
        env:
        # Services of this node
        - name: SERVICES
          value: "master, acl, activity, context, control, events, instance, next, query, sequence, timer, queue"
        # Broker settings - transporter
        - name: TRANSPORTER_NATS
          value: "nats://nats:4222" 
        # master+keys service settings
        - name: MASTER_TOKEN
          valueFrom:
            secretKeyRef:
              name: master-token
              key: token
        - name: SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              name: service-token
              key: token
        # Service settings - agent id + token -> control
        - name: SERVICE_ID
          valueFrom:
            secretKeyRef:
              name: flow-service
              key: id
        - name: SERVICE_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: flow-service
              key: token
        # Service settings - admin group -> ??
        - name: ADMIN_GROUP_ID
          valueFrom:
            secretKeyRef:
              name: admin-group
              key: id
        - name: EVENT_OWNER_ID
          valueFrom:
            secretKeyRef:
              name: admin-group
              key: id
        # Service settings - db -> master,keys, context
        - name: CASSANDRA_CONTACTPOINTS
          value: "cassandra"
        - name: CASSANDRA_DATACENTER
          value: "datacenter1"
        - name: CASSANDRA_KEYSPACE_KEYS
          value: "imicros_keys"
        - name: CASSANDRA_KEYSPACE_QUEUE
          value: "imicros_queue"
        - name: CASSANDRA_PORT
          value: "9042"
        - name: CASSANDRA_USER
          valueFrom:
            secretKeyRef:
              name: cassandra-root
              key: user
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cassandra-root
              key: password
        # Service settings - db -> acl, control, instance, query
        - name: NEO4J_URI
          value: "bolt://neo4j:7687"
        - name: NEO4J_USER
          valueFrom:
            secretKeyRef:
              name: neo4j-root
              key: user
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j-root
              key: password
        # Service settings - jwt secret -> acl
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
          