apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: neo4j
      folder: data
