apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: minio
      folder: data
