apiVersion: v1
kind: PersistentVolume
metadata:
  name: development
  labels:
    type: local
    app: development
    folder: modules
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/admin/modules"