apiVersion: v1
kind: Secret
metadata:
  name: minio-user-credentials
  namespace: development
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  # 'development' base64 encoded with $ echo -n "development" | base64
  username: ZGV2ZWxvcG1lbnQ=