apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: development
  namespace: development
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: development
      folder: modules