apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: nats-exporter
    app.kubernetes.io/instance: latest
spec:
  endpoints:
    - port: http
      honorLabels: true
    - path: /metrics
  namespaceSelector:
    matchNames:
      - nats
  selector:
    matchLabels:
      app.kubernetes.io/name: nats-exporter
      app.kubernetes.io/instance: latest
