apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: redis
  labels:
    app.kubernetes.io/name: redis-exporter
    app.kubernetes.io/instance: latest
    app: redis-exporter
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9121
      protocol: TCP
      name: http
  selector:
    app: redis-exporter