apiVersion: v1
kind: Service
metadata:
  name: nats-exporter
  namespace: nats
  labels:
    app.kubernetes.io/name: nats-exporter
    app.kubernetes.io/instance: latest
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 7777
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nats-exporter
    app.kubernetes.io/instance: latest
