apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-exporter
  namespace: nats
  labels:
    app.kubernetes.io/name: nats-exporter
    app.kubernetes.io/instance: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nats-exporter
      app.kubernetes.io/instance: latest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nats-exporter
        app.kubernetes.io/instance: latest
    spec:
      containers:
        - name: nats-exporter
          args:
            - "-varz"
            - "-accstatz"
            - "-channelz"
            - "-connz"
            - "-connz_detailed"
            - "-routez"
            - "-serverz"
            - "-subz"
            - "-gatewayz"
            - "-jsz=all"
            - "-leafz"
            - "http://nats.nats.svc:8222"
          image: natsio/prometheus-nats-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7777
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
            requests:
              memory: 64Mi
              cpu: 500m
            limits:
              memory: 64Mi
              cpu: 500m
