apiVersion: v1
kind: Service
metadata:
  name: nats-node
  labels:
    app: nats
spec:
  selector:
    app: nats
  type: NodePort
  ports:
  - name: client
    port: 4222
    targetPort: 4222
    protocol: TCP
    nodePort: 31131
  - name: monitor
    port: 8222
    targetPort: 8222
    protocol: TCP
    nodePort: 31130
