apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: nats
  labels:
    app: nats
spec:
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
    targetPort: 4222
    protocol: TCP
  - name: monitor
    port: 8222
    targetPort: 8222
    protocol: TCP
