apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imicros-gateway
  annotations:
    kubernetes.io/ingress.class: traefik
#   Keiner der Versuche funktioniert -> Fehlermeldung: Middleware existiert nicht....
#   Daher /api als default path in imicros-gateway konfiguriert!
#    traefik.ingress.kubernetes.io/router.middlewares: traefik-stripprefix
#    traefik.ingress.kubernetes.io/router.middlewares: stripprefix@kubernatescrd
#    traefik.ingress.kubernetes.io/router.middlewares: traefik-stripprefix@kubernates
#    traefik.ingress.kubernetes.io/router.middlewares: traefik-stripprefix@kubernetes
#    traefik.ingress.kubernetes.io/router.middlewares: stripprefix@kubernetes
#    traefik.ingress.kubernetes.io/request-modifier: "ReplacePath: /api"
#    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
#    traefik.ingress.kubernetes.io/router.middlewares: default-stripprefix@kubernetes
#    traefik.ingress.kubernetes.io/router.middlewares: default-stripprefix
#    traefik.ingress.kubernetes.io/router.middlewares: default-stripprefix@kubernetescrd
#    traefik.ingress.kubernetes.io/router.middlewares: traefik-api@kubernetes
#    traefik.ingress.kubernetes.io/router.middlewares: traefik-api@kubernetescrd
spec:
  rules:
    - host: home.server
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name:  imicros-gateway
                port:
                  number: 3000
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name:  imicros-gateway
                port:
                  number: 3000
