apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-deployment
  namespace: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      securityContext:
        runAsUser: 1001
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: cassandra
      - name: jmx-secret
        secret:
            defaultMode: 0666
            secretName: cassandra-jmx
      - name: scripts
        configMap:
            name: cassandra
            defaultMode: 0775
      containers:
      - name: cassandra
        image: bitnami/cassandra:latest
        command: ['/bin/sh', '-c', '/usr/local/apache-cassandra/scripts/run_override.sh']
        env:
        - name: CASSANDRA_USER
          valueFrom:
            secretKeyRef:
              name: cassandra-root
              key: user
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cassandra-root
              key: password
        - name: JVM_OPTS
          value: "    -XX:+AlwaysPreTouch
                      -Dorg.slf4j.simpleLogger.showDateTime=true
                      -Dorg.slf4j.simpleLogger.dateTimeFormat=\"yyyy-MM-dd'T'HH:mm:ss\"
                      -Dcom.sun.management.jmxremote.ssl=false
                      -Dcom.sun.management.jmxremote.authenticate=false
                      -Dcom.sun.management.jmxremote.port=7199
                      -Dcom.sun.management.jmxremote.local.only=false
                      -Dnetworkaddress.cache.ttl=15"
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7348
          name: jmx
        - containerPort: 9042
          name: cql
        volumeMounts:
        - name: data # must match the volume name, above
          mountPath: "/bitnami"
        - name: scripts
              mountPath: /usr/local/apache-cassandra/scripts
          
