apiVersion: v1
kind: PersistentVolume
metadata:
  name: imicros-dev-5-pv1
  labels:
    app: cassandra
spec:
  claimRef:
    name: server-data-dev-cluster-dev-datacenter-default-sts-0
    namespace: cass-operator
  capacity:
    storage: 80Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cassandra-local-ssd
  local:
    path: /data/volumes/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - imicros-dev-5
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: imicros-dev-6-pv1
  labels:
    app: cassandra
spec:
  claimRef:
    name: server-data-dev-cluster-dev-datacenter-default-sts-1
    namespace: cass-operator
  capacity:
    storage: 80Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cassandra-local-ssd
  local:
    path: /data/volumes/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - imicros-dev-6
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: imicros-dev-7-pv1
  labels:
    app: cassandra
spec:
  claimRef:
    name: server-data-dev-cluster-dev-datacenter-default-sts-2
    namespace: cass-operator
  capacity:
    storage: 80Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cassandra-local-ssd
  local:
    path: /data/volumes/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - imicros-dev-7
