apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: cassandra
  labels:
    app: cassandra
spec:
  ports:
  - name: storage
    port: 7000
    targetPort: 7000
    protocol: TCP
  - name: native
    port: 9042
    targetPort: 9042
    protocol: TCP
  selector:
    app: cassandra
