apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra
  namespace: cassandra
  labels:
    type: local
    app: cassandra
    folder: data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/cassandra-dev-1"
