apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: cassandra
      folder: data
