apiVersion: v1
kind: Namespace
metadata:
  name: wireguard-system
  labels:
    name: wireguard-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    name: minio
---
apiVersion: v1
kind: Namespace
metadata:
  name: nats
  labels:
    name: nats
---
apiVersion: v1
kind: Namespace
metadata:
  name: cass-operator
  labels:
    name: cass-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    name: redis

