apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-exporter
  namespace: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra-exporter
    spec:
      containers:
      - name: cassandra-exporter
        image: bitnami/cassandra-exporter:latest
        command: [ "java", "-jar", "./cassandra_exporter.jar", "./config/config.yml" ]
        env:
        - name: JVM_OPTS
          value: "-XX:MaxRAMFraction=2
                      -XX:+AlwaysPreTouch
                      -Dorg.slf4j.simpleLogger.showDateTime=true
                      -Dorg.slf4j.simpleLogger.dateTimeFormat=\"yyyy-MM-dd'T'HH:mm:ss\"
                      -Dcom.sun.management.jmxremote.ssl=false
                      -Dcom.sun.management.jmxremote.authenticate=false
                      -Dcom.sun.management.jmxremote.port=5555
                      -Dcom.sun.management.jmxremote.local.only=false
                      -Dnetworkaddress.cache.ttl=15"
        ports:
          - name: metrics
            containerPort: 8080
            protocol: TCP
          - name: jmx-exporter
            containerPort: 5555
        livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 180
        readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 180
            timeoutSeconds: 45
        resources:
            limits:
                cpu: 300m
                memory: 500Mi
            requests:
                cpu: 300m
                memory: 500Mi
        volumeMounts:
            - name: cassandra-exporter-config
              mountPath: /opt/bitnami/cassandra-exporter/config
      volumes:
        - name: cassandra-exporter-config
          configMap:
            defaultMode: 420
            name: cassandra-exporter
