apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: dev-cluster
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.7.1
    metadataVersion: 3.7-IV4
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    storage:
      type: persistent-claim
      class: ssd
      size: 10Gi
      volumeMode: Block
      deleteClaim: false
      kraftMetadata: shared
      overrides:
        - broker: 0
          class: ssd-dev-2
        - broker: 1
          class: ssd-dev-3
        - broker: 2
          class: ssd-dev-4
  entityOperator:
    topicOperator: {}
    userOperator: {}