apiVersion: v1
kind: PersistentVolume
metadata:
  name: imicros-dev-8-pv1 
  labels:
    strimzi.io/cluster: dev-cluster
spec:
  capacity:
    storage: 80Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-local-storage
  local:
    path: /data/volumes/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - imicros-dev-8
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: imicros-dev-9-pv1
  labels:
    strimzi.io/cluster: dev-cluster
spec:
  capacity:
    storage: 80Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-local-storage
  local:
    path: /data/volumes/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - imicros-dev-9
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: imicros-dev-10-pv1
  labels:
    strimzi.io/cluster: dev-cluster
spec:
  capacity:
    storage: 80Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-local-storage
  local:
    path: /data/volumes/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - imicros-dev-10