apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-cluster-dev-pool-0
  labels:
    strimzi.io/cluster: dev-cluster
spec:
  claimRef:
    name: dev-cluster-dev-pool-0
    namespace: kafka
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/volumes/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dev-imicros-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-cluster-dev-pool-1
  labels:
    strimzi.io/cluster: dev-cluster
spec:
  claimRef:
    name: dev-cluster-dev-pool-1
    namespace: kafka
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/volumes/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dev-imicros-3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kdev-cluster-dev-pool-2
  labels:
    strimzi.io/cluster: dev-cluster
spec:
  claimRef:
    name: dev-cluster-dev-pool-2
    namespace: kafka
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/volumes/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dev-imicros-4