apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: redis-exporter
    release: kube-prom-stack
spec:
  endpoints:
    - port: http
      honorLabels: true
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - redis
  selector:
    matchLabels:
      app: redis-exporter
