apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
Metadata:
  labels:
    app: redis-exporter
    name: redis-exporter
  namespace: monitor
  spec:
  endpoints:
  - interval: 15s
    port: exporter-port
  selector:
    matchLabels:
      app: redis-exporter