apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-web
  namespace: cass-operator
  labels:
    app.kubernetes.io/name: cassandra-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cassandra-web
  template:
    metadata:
      labels:
        app: cassandra-web
        app.kubernetes.io/name: cassandra-web
    spec:
      containers:
        - name: cassandra-web
          image: "ipushc/cassandra-web:latest"
          imagePullPolicy: IfNotPresent
          env:
          - name: HOST_PORT
            value: "8080"
          - name: CASSANDRA_HOST
            value: "dev-cluster-dev-datacenter-all-pods-service.cass-operator.svc.cluster.local"
          - name: CASSANDRA_PORT
            value: "9042"
          - name: CASSANDRA_USERNAME
            value: "cassandraweb"
          - name: CASSANDRA_PASSWORD
            value: "cassandraweb"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "500m"
              memory: "500Mi"
