apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-web-deployment
  namespace: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra-web
    spec:
      containers:
      - name: cassandra-web
        image: ipushc/cassandra-web
        env:
        - name: HOST_PORT
          value: '8083'
        - name: CASSANDRA_HOST
          value: 'cassandra.cassandra.svc.cluster.local'
        - name: CASSANDRA_PORT
          value: '9042'
        - name: CASSANDRA_USER
          valueFrom:
            secretKeyRef:
              name: cassandra-root
              key: user
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cassandra-root
              key: password
        ports:
        - containerPort: 8083
          name: web
          
