apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-web-deployment
  namespace: cass-operator
spec:
  selector:
    matchLabels:
      app: cassandra-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra-web
    spec:
      containers:
      - name: cassandra-web
        image: ipushc/cassandra-web
        env:
        - name: HOST_PORT
          value: "3000"
        # must be adopted according the clusterIP of the cassandra service
        - name: CASSANDRA_HOST
          value: "10.152.183.175"
        - name: CASSANDRA_PORT
          value: "9042"
        - name: CASSANDRA_USERNAME
          valueFrom:
            secretKeyRef:
              name: dev-cluster-superuser
              key: username
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-cluster-superuser
              key: password
        ports:
        - containerPort: 3000
          name: http
          
