apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-web-deployment
  namespace: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra-web
    spec:
      containers:
      - name: cassandra-web
        image: markusgulden/cassandra-web
        env:
        # must be adopted according the clusterIP of the cassandra service
        - name: CASSANDRA_HOST_IPS
          value: '10.152.183.175'
        - name: CASSANDRA_PORT
          value: '9042'
        - name: CASSANDRA_USER
          valueFrom:
            secretKeyRef:
              name: cassandra-root
              key: user
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cassandra-root
              key: password
        ports:
        - containerPort: 3000
          name: web
          
