apiVersion: v1
kind: Service
metadata:
  name: cassandra-web
  namespace: cassandra
  labels:
    app: cassandra-web
spec:
  ports:
  - name: web
    port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    app: cassandra-web