apiVersion: v1
kind: Service
metadata:
  name: cassandra-web
  namespace: cass-operator
  labels:
    app: cassandra-web
spec:
  ports:
  - name: web
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: cassandra-web