apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-nginx
spec:
  rules:
  - host: test.imicros.de # CHANGE ME!
    http:
      paths:
      # The * is needed so that all traffic gets redirected to nginx
      - path: /*
        backend:
          service:
            name: demo-nginx
            port:
              number: 80