apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j
  labels:
    type: local
    app: neo4j
    folder: data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/neo4j-test-1"