apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
  labels:
    type: local
    app: minio
    folder: data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/admin/minio/data"
