apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio
      containers:
      - name: minio
        #image: minio/minio:latest
        #image: quay.io/minio/minio:RELEASE.2022-04-29T01-27-09Z
        image: minio/minio
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: password
        - name: MINIO_REGION_NAME
          value: "eu-central-1"
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: "public"
        #- name: MINIO_BROWSER_REDIRECT_URL
        #  value: https://dev.imicros.de/minio/
        command: 
        - "/bin/sh"
        - "-ce"
        - "/usr/bin/docker-entrypoint.sh minio server /data -S /etc/minio/certs/ --address :9000 --console-address :9001"
        ports:
        - name: api
          containerPort: 9000
        - name: console
          containerPort: 9001
        volumeMounts:
          - name: storage
            mountPath: /data
