apiVersion: v1
kind: Secret
metadata:
  name: console-user-credentials
  namespace: minio
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: CONSOLE_SECRET_KEY
data:
  # 'console' base64 encoded with $ echo -n "console" | base64
  CONSOLE_ACCESS_KEY:  Y29uc29sZQ==