apiVersion: v1
kind: Service
metadata:
  name: minio-pod
  namespace: minio
  labels:
    app: minio-pod
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio        