apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: minio
type: Opaque
stringData:
  config.env: |-
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
    export MINIO_PROMETHEUS_AUTH_TYPE="public"
    export MINIO_PROMETHEUS_JOB_ID="minio-prom-job"
    export MINIO_PROMETHEUS_URL="http://kube-prom-stack-kube-prome-prometheus.observability.svc.cluster.local:9090"
