apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: minio-metrics
  namespace: observability
  labels:
    app: minio-metrics
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  namespaceSelector:
    matchNames:
      - kafka
  podMetricsEndpoints:
  - path: /metrics
    port: http
---