apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-cluster
  namespace: observability
  labels:
    app.kubernetes.io/name: minio-cluster
    release: kube-prom-stack
spec:
  endpoints:
    - port: http-minio
      path: /minio/v2/metrics/cluster
      scrapeTimeout: 15s
      interval: 15s
  namespaceSelector:
    matchNames:
      - minio
  selector:
    matchLabels:
      v1.min.io/tenant: minio
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-bucket
  namespace: observability
  labels:
    app.kubernetes.io/name: minio-bucket
    release: kube-prom-stack
spec:
  endpoints:
    - port: http-minio
      path: /minio/v2/metrics/bucket
      scrapeTimeout: 15s
      interval: 15s
  namespaceSelector:
    matchNames:
      - minio
  selector:
    matchLabels:
      v1.min.io/tenant: minio
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-node
  namespace: observability
  labels:
    app.kubernetes.io/name: minio-node
    release: kube-prom-stack
spec:
  endpoints:
    - port: http-minio
      path: /minio/v2/metrics/node
      scrapeTimeout: 15s
      interval: 15s
  namespaceSelector:
    matchNames:
      - minio
  selector:
    matchLabels:
      v1.min.io/tenant: minio
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-resource
  namespace: observability
  labels:
    app.kubernetes.io/name: minio-resource
    release: kube-prom-stack
spec:
  endpoints:
    - port: http-minio
      path: /minio/v2/metrics/resource
      scrapeTimeout: 15s
      interval: 15s
  namespaceSelector:
    matchNames:
      - minio
  selector:
    matchLabels:
      v1.min.io/tenant: minio
